### ISSUE TITLE
Add anchor button option to profile builder

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/tinymce#74]
Is it possible to add anchor button as an option with the profile builder?

Looks like it's possible to add an [anchor button](https://www.tiny.cloud/docs/tinymce/latest/anchor/) manually in the profile JSON:

```
"toolbar": "bold italic blockquote | bullist numlist | backdroplink backdropunlink anchor | visualblocks removeformat fullscreen",
"plugins": "lists backdroplink visualblocks fullscreen autoresize anchor",
```

**Comment by herbdool** [comment]
@indigoxela got a PR, seems to be easier than I thought.

**Comment by herbdool** [comment]
Oh, not done. The button is there but not the plugin.

**Comment by herbdool** [comment]
Fixed.

**Comment by indigoxela** [comment]
Yes, there are some plugins not added to the builder - for different reasons.

When I first looked at the anchor plugin, I didn't find that it provides anything that's not already possible via the backdroplink plugin.
But, sure, why not add it. The indicator icon's nice, I guess. Will take a closer look later.

**Comment by indigoxela** [comment]
Still not a huge fan of that plugin, but I understand, that people may want it.
Initially I thought about coming up with a better alternative, but time flies... and the plugin is OK as-is. :wink: 

Here's an alternate [PR](https://github.com/backdrop-contrib/tinymce/pull/76), which also prevents a "responsibility conflict" with the backdroplink plugin. Want to test?

**Comment by herbdool** [comment]
I've a client where they are using the CKEditor version of the anchor button right now, and may need it here if we switch them. I figure it's easier to add here than create a separate module.

**Comment by herbdool** [comment]
@indigoxela I've tested your PR and it fully works. No conflict.

Out of curiosity I tried to set an anchor with the backdroplink plugin by filling in the Unique Identifier and leaving the href blank. But it disappears. Not sure if that's TinyMCE cleaning up or if I'm doing it wrong. But regardless it's less confusing to have a dedicated button and an icon on the actual anchor. If I find it confusing, then probably so do my clients.

**Comment by indigoxela** [comment]
> Not sure if that's TinyMCE cleaning up or if I'm doing it wrong. 

Ah, right, that was the point...

The trouble adding an empty link (no href value) is partly caused by the core link dialog, partly the backdroplink plugin. :wink:

A good reason to add the anchor plugin to the builder.
